# Generated by Django 3.1.2 on 2021-02-01 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ECTS', models.IntegerField()),
                ('course_name', models.CharField(max_length=33)),
                ('type', models.CharField(choices=[('W', 'wykład'), ('C', 'ćwiczenia'), ('L', 'laboratoria')], max_length=1)),
                ('final', models.FloatField(blank=True, default=0)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('webpage', models.CharField(blank=True, max_length=60)),
                ('html', tinymce.models.HTMLField(default='')),
            ],
            options={
                'verbose_name_plural': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='studentHelper.course')),
                ('weight', models.FloatField()),
                ('minimum', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Thresholds',
            fields=[
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='studentHelper.course')),
                ('p_3_0', models.FloatField()),
                ('p_3_5', models.FloatField()),
                ('p_4_0', models.FloatField()),
                ('p_4_5', models.FloatField()),
                ('p_5_0', models.FloatField()),
                ('p_5_5', models.FloatField()),
                ('type', models.CharField(choices=[('PKT', 'punkty'), ('MARK', 'ocena'), ('PERC', 'procent')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ACTIV', 'aktywność'), ('EXAM', 'egzamin'), ('QUIZ', 'kartkówka'), ('TEST', 'kolokwium'), ('LIST', 'lista zadań')], max_length=7)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('pred_time', models.IntegerField()),
                ('actual_time', models.IntegerField(blank=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentHelper.course')),
            ],
        ),
        migrations.CreateModel(
            name='Modyfication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod', models.CharField(choices=[('MINUS', '-'), ('PLUS', '+')], max_length=5)),
                ('val', models.FloatField()),
                ('type', models.CharField(choices=[('PKT', 'punkty'), ('MARK', 'ocena'), ('PERC', 'procent')], max_length=5)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentHelper.course')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField()),
                ('weight', models.FloatField()),
                ('mark_type', models.CharField(choices=[('PKT', 'pkt'), ('MARK', 'ocena'), ('PERC', 'procent')], max_length=7)),
                ('mark_form', models.CharField(choices=[('ACTIV', 'aktywność'), ('EXAM', 'egzamin'), ('QUIZ', 'kartkówka'), ('TEST', 'kolokwium'), ('LIST', 'lista zadań')], max_length=7)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentHelper.course')),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField()),
                ('achieved', models.CharField(choices=[('A', 'osiągnięty'), ('E', 'przedawniony'), ('N', 'nieosiągnięty')], max_length=1)),
                ('type', models.CharField(choices=[('A', 'aktywność'), ('M', 'ocena'), ('O', 'inne')], max_length=1)),
                ('value', models.FloatField()),
                ('description', models.CharField(max_length=128)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentHelper.course')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('file_path', models.FileField(upload_to='')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentHelper.course')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('period_type', models.CharField(choices=[('ONCE', 'Pojedyncze wydarzenie'), ('DAILY', 'Codziennie'), ('WEEKLY', 'Co tydzień'), ('MONTHLY', 'Co miesiąc'), ('YEARLY', 'Rocznie')], max_length=7)),
                ('whole_day', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('event_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='studentHelper.events')),
                ('course', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CourseEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('period_type', models.CharField(choices=[('ONCE', 'Pojedyncze wydarzenie'), ('DAILY', 'Codziennie'), ('WEEKLY', 'Co tydzień'), ('MONTHLY', 'Co miesiąc'), ('YEARLY', 'Rocznie')], max_length=7)),
                ('whole_day', models.BooleanField(default=False)),
                ('description', models.CharField(choices=[('ACTIV', 'aktywność'), ('EXAM', 'egzamin'), ('QUIZ', 'kartkówka'), ('TEST', 'kolokwium'), ('LIST', 'lista zadań')], max_length=20)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentHelper.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentHelper.teacher'),
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('ACTIV', 'aktywność'), ('EXAM', 'egzamin'), ('QUIZ', 'kartkówka'), ('TEST', 'kolokwium'), ('LIST', 'lista zadań')], max_length=5)),
                ('type', models.CharField(choices=[('PKT', 'punkty'), ('MARK', 'ocena'), ('PERC', 'procent')], max_length=5)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentHelper.course')),
            ],
        ),
    ]
