# Generated by Django 3.1.2 on 2020-11-14 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentHelper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ECTS', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('W', 'lecture'), ('C', 'exercises'), ('L', 'laboratory')], max_length=1)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('webpage', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='studentHelper.course')),
                ('group', models.BooleanField()),
                ('lab_elements', models.IntegerField(blank=True)),
                ('exer_elements', models.IntegerField(blank=True)),
                ('lect_elements', models.IntegerField(blank=True)),
                ('lab_weight', models.IntegerField(blank=True)),
                ('exer_weight', models.IntegerField(blank=True)),
                ('lect_weight', models.IntegerField(blank=True)),
                ('formula', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('pred_time', models.TimeField()),
                ('actual_time', models.TimeField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentHelper.course')),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField()),
                ('type', models.CharField(choices=[('A', 'activity'), ('M', 'marks'), ('O', 'others')], max_length=1)),
                ('description', models.CharField(max_length=128)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentHelper.course')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=64)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentHelper.course')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('period_type', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('even', 'Even'), ('odd', 'Odd')], max_length=7)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('event_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='studentHelper.events')),
                ('course', models.BooleanField()),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentHelper.teacher'),
        ),
    ]
