# Generated by Django 3.1.2 on 2020-11-14 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentHelper', '0002_auto_20201114_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'Teacher'},
        ),
    ]
