# Generated by Django 3.1.3 on 2020-11-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentHelper', '0005_auto_20201116_1146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
