# Generated by Django 3.1.3 on 2020-11-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentHelper', '0006_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='final',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
