# Generated by Django 3.1.2 on 2020-11-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentHelper', '0007_auto_20201116_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='course',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='period_type',
            field=models.CharField(choices=[('ONCE', 'Pojedyncze wydarzenie'), ('DAILY', 'Codziennie')], max_length=7),
        ),
    ]
