# Generated by Django 3.1.3 on 2020-11-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentHelper', '0008_auto_20201122_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='final',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('W', 'wykład'), ('C', 'ćwiczenia'), ('L', 'laboratoria')], max_length=1),
        ),
        migrations.AlterField(
            model_name='goals',
            name='type',
            field=models.CharField(choices=[('A', 'aktywność'), ('M', 'ocena'), ('O', 'inne')], max_length=1),
        ),
        migrations.AlterField(
            model_name='marks',
            name='mark_type',
            field=models.CharField(choices=[('PLUS', '+'), ('MINUS', '-'), ('PKT', 'pkt'), ('MARK', 'ocena')], max_length=7),
        ),
    ]
