# Generated by Django 3.1.3 on 2020-12-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentHelper', '0009_auto_20201128_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
