# Generated by Django 3.1.2 on 2020-12-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentHelper', '0010_auto_20201212_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
        migrations.AddField(
            model_name='events',
            name='whole_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='period_type',
            field=models.CharField(choices=[('ONCE', 'Pojedyncze wydarzenie'), ('DAILY', 'Codziennie'), ('WEEKLY', 'Co tydzień'), ('MONTHLY', 'Co miesiąc'), ('YEARLY', 'Rocznie')], max_length=7),
        ),
    ]
