# Generated by Django 3.1.3 on 2020-12-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentHelper', '0010_auto_20201211_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=33),
        ),
    ]
