# Generated by Django 3.1.2 on 2020-12-12 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentHelper', '0011_auto_20201212_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentHelper.course'),
        ),
    ]
