# Generated by Django 3.1.2 on 2020-12-12 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentHelper', '0012_auto_20201212_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('ACTIV', 'aktywność'), ('EXAM', 'egzamin'), ('QUIZ', 'kartkówka'), ('TEST', 'kolokwium'), ('LIST', 'lista zadań')], max_length=5)),
                ('weight', models.FloatField()),
                ('type', models.CharField(choices=[('POINT', 'punkty'), ('MARK', 'ocena'), ('PERC', 'procent')], max_length=5)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentHelper.course')),
            ],
        ),
    ]
