# Generated by Django 3.1.2 on 2020-12-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentHelper', '0013_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='thresholds',
            name='k_5_5',
        ),
        migrations.RemoveField(
            model_name='thresholds',
            name='p_2_0',
        ),
    ]
